# Generated by Django 4.2 on 2023-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('sizes', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('2xl', '2 extra large'), ('3xl', '3 extra large'), ('4xl', '4 extra large')], default='l', max_length=3)),
            ],
        ),
    ]
